from addon.routes import home
from addon.routes import listen_now
from addon.routes import top_charts
from addon.routes import new_releases
from addon.routes import my_library
from addon.routes import browse_stations
from addon.routes import generic
from addon.routes import actions
from addon.routes import files
